### ISSUE TITLE
A little bug

### ISSUE THREAD

**Issue by Nikaladze** [Antol/APAutocompleteTextField#1]
There is a little bug when I trying to type first letter from the phrase. For example, if my first character will be 'a' - there will be: 

```
APAutocompleteTextFieldExample[1487:70b] 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', 
reason: 'Wrong completion string'
```

So, I have modified your code (just a little) by adding one condition to autocompleteTextField:complitedStringForOriginString in APViewController.m:

```
if ((originStringRange.location == NSNotFound) || (originStringRange.location != 0) ) {
        complitedString = nil;
    }
```

**Comment by Antol** [comment]
Oh. Yes, of course. I missed it. But this is just an example, so that's okay. I'll fix it, thanks
